import React, {useState} from "react";
import { CheckCircle2, FileDown, Network, ShieldCheck, XCircle, ClipboardCheck, MapPin, Eye, Activity } from "lucide-react";
import MapMock from "./MapMock";
import { sites } from "../data/demoData";
import { PageTitle, StatusBadge, InfoLine } from "./PagePrimitives";

export default function SiteAnalysis({siteId="SITE-A",onBack,onSetSite,onReview}) {
  const selected = sites[siteId] || sites["SITE-A"];
  const [tab,setTab]=useState("overview");
  return <div className="page">
    <div className="crumb"><button onClick={onBack}>Search results</button><span>/</span><b>Site Analysis</b></div>
    <PageTitle title={selected.id} subtitle={selected.title + " - local evidence workspace"} actions={<div className="titleRight"><StatusBadge status={selected.confidence >= 80 ? "High confidence" : selected.confidence >= 60 ? "Review" : "Suppressed"}/><span className="modeMini">DEMO</span></div>} />
    <div className="siteMeta"><span><MapPin size={14}/>{selected.riverDistance}</span><span><Activity size={14}/>{selected.observations} observations</span><span><Eye size={14}/>{selected.usable} usable</span><span><ShieldCheck size={14}/>Evidence-first</span></div>
    <div className="siteTabs">{[["overview","Overview"],["change","Change Analysis"],["temporal","Temporal Evidence"],["similar","Similar Sites"],["provenance","Provenance"]].map(([id,label])=><button key={id} className={tab===id?"selected":""} onClick={()=>setTab(id)}>{label}</button>)}</div>
    {tab==="overview" && <div className="analysisGrid expanded">
      <section className="panel evidence"><div className="panelHead"><div><h2>Before / After Comparison</h2><p>Same selected site, two observations from the local sequence</p></div><div className="tabs"><button className="selected">Optical</button><button>SAR</button><button>Change Mask</button></div></div><div className="beforeAfter"><div className="satImage before"><span>BEFORE</span><div className="terrain"></div></div><div className="arrow">→</div><div className="satImage after"><span>AFTER</span><div className="terrain changed"></div></div></div><div className="imageMeta"><span>{selected.beforeLabel}</span><span>{selected.afterLabel}</span></div></section>
      <section className="panel why"><div className="panelHead"><div><h2>Why this result?</h2><p>Confidence is not shown without supporting evidence.</p></div><ShieldCheck size={18}/></div><div className="scoreRows"><div><span>Semantic match</span><b>{selected.confidence-3}%</b></div><div><span>Temporal persistence</span><b>{selected.confidence}%</b></div><div><span>Spatial context</span><b>{selected.confidence-1}%</b></div><div><span>Image quality</span><b>{selected.confidence+2 > 99 ? 99 : selected.confidence+2}%</b></div></div><ul>{selected.evidence.map(x=><li key={x}><CheckCircle2 size={14}/>{x}</li>)}</ul></section>
      <section className="panel timelinePanel"><div className="panelHead"><div><h2>Temporal Evidence</h2><p>First supported change is derived from the usable sequence.</p></div><StatusBadge status={selected.usable+" usable"}/></div><div className="timeline">{selected.timeline.map((x,i)=><div className={x[1].toLowerCase().includes("change")||x[1].toLowerCase().includes("construction") ? "event active":"event"} key={x[0]}><span></span><small>{x[0]}</small><b>{x[1]}</b></div>)}</div><div className="earliest"><b>Earliest supported change</b><strong>{selected.earliest}</strong></div></section>
      <section className="panel quality"><div className="panelHead"><div><h2>Quality & False-Alarm Assessment</h2><p>Confounders are surfaced explicitly.</p></div><StatusBadge status={selected.id==="SITE-C"?"Suppressed":"Low risk"}/></div>{Object.entries(selected.quality).map(([label,value])=><InfoLine key={label} label={label} value={value} kind={String(value).toLowerCase().includes("high")?"warn":"ok"}/>)}</section>
      <section className="panel mapPanel"><div className="panelHead"><div><h2>Location Context</h2><p>AOI, river corridor and candidate context</p></div></div><MapMock compact selected={selected.id}/></section>
      <section className="panel actionsPanel"><div className="panelHead"><div><h2>Analyst Tools</h2><p>Local workflow actions</p></div></div><div className="actionStack"><button onClick={()=>onReview(selected.id,"confirmed")} className="primary"><CheckCircle2 size={14}/> Confirm Change</button><button onClick={()=>onReview(selected.id,"rejected")} className="danger"><XCircle size={14}/> Reject / False Alarm</button><button onClick={()=>onSetSite("SITE-B")} className="ghost"><Network size={14}/> Find Similar Sites</button><button className="ghost"><ClipboardCheck size={14}/> Add to Review Queue</button><button className="ghost"><FileDown size={14}/> Export Evidence</button></div></section>
      <section className="panel provenance"><div className="panelHead"><div><h2>Data Provenance</h2><p>Every result carries a local provenance record.</p></div><StatusBadge status="Local"/></div><div className="provGrid"><div>Source asset<strong>Local manifest entry</strong></div><div>Acquisition<strong>From staged metadata</strong></div><div>Sensor<strong>Manifest-defined</strong></div><div>Processing<strong>Fixture/demo pipeline</strong></div><div>Model<strong>Not connected in UI stage</strong></div><div>Index<strong>Local fixture index</strong></div><div>Decision<strong>Updated in session</strong></div><div>Checksum<strong>Manifest field</strong></div></div></section>
    </div>}
    {tab!=="overview" && <section className="panel placeholderModule"><h2>{tab.replace("-"," ")} view</h2><p>This tab reuses the same selected-site data and is wired for the next integration layer. Use the Overview tab for the full demo path.</p></section>}
  </div>
}
